"""Single source of truth for page config + global CSS.

Streamlit isolates `st.markdown` / `st.set_page_config` per page — each
file under `pages/` renders in its own runtime, so any CSS injected in
`app.py` does not reach Admin / Game / Help. Without this module the
main dashboard looked dark while the sidebar pages reverted to
Streamlit's default light theme.

Every page (the main app + every file in `pages/`) calls
``setup_page(...)`` first thing in render so the brand, favicon, and
custom CSS are applied uniformly.
"""

import streamlit as st

from stock_toolkit.ui.icons import icon


# Single light theme applied uniformly to every page. Selectors override
# Streamlit's auto theme behaviour so browsers that follow OS dark mode
# still render the dashboard in its intended look.
#
# Palette:
#   --bg          #fafbfc   off-white main surface
#   --sidebar     #f1f4f8   subtly tinted to separate from main
#   --border      #d6dde6   1 px hairline that defines panels
#   --ink         #1a2535   primary text — high-contrast slate
#   --muted       #5a6b7e   secondary labels
#   --accent      #1e2f40   sidebar heading / nav text
_THEME_CSS = """
<style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300;400;500&family=IBM+Plex+Sans:wght@300;400;500;600&display=swap');

html, body, [class*="css"] {
    font-family: 'IBM Plex Sans', sans-serif;
}

/* App background — single source of truth across main + pages. */
[data-testid="stAppViewContainer"],
[data-testid="stMain"],
.main {
    background: #fafbfc;
    color: #1a2535;
}

/* Metric numbers */
[data-testid="stMetricValue"] {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 1.4rem !important;
    font-weight: 500;
    color: #1a2535;
}

/* Dataframe / table */
[data-testid="stDataFrame"] {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 0.82rem;
}

/* Score bar cells */
.score-bar {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 0.78rem;
    color: #5a6b7e;
}

/* Header strip */
.header-strip {
    background: linear-gradient(90deg, #f1f4f8 0%, #e6ecf3 100%);
    border-bottom: 1px solid #d6dde6;
    padding: 0.6rem 1rem;
    margin: -1rem -1rem 1.5rem -1rem;
    display: flex;
    align-items: center;
    gap: 0.6rem;
}
.header-title {
    font-family: 'IBM Plex Mono', monospace;
    font-weight: 500;
    font-size: 1.05rem;
    color: #1a2535;
    letter-spacing: 0.04em;
}

/* Sidebar — light tint, same surface across main + every page. */
[data-testid="stSidebar"] {
    background: #f1f4f8;
    border-right: 1px solid #d6dde6;
}
[data-testid="stSidebar"] label,
[data-testid="stSidebar"] p,
[data-testid="stSidebar"] span,
[data-testid="stSidebar"] li {
    color: #5a6b7e !important;
    font-size: 0.82rem !important;
}
[data-testid="stSidebar"] h1,
[data-testid="stSidebar"] h2,
[data-testid="stSidebar"] h3,
[data-testid="stSidebar"] h4 {
    color: #1a2535 !important;
}

/* Multiselect / select chips ("tags") — Streamlit ships them on a
   red primary surface. The broad sidebar muted-text rule above
   makes the chip text low-contrast on red, so override here. The
   close-button ✕ shares the same colour for consistency. Scoped
   globally because the same selector is used inside multiselects
   in the main page area (Score symbols, etc.). */
[data-baseweb="tag"],
[data-baseweb="tag"] span,
[data-baseweb="tag"] svg {
    color: #ffffff !important;
    fill:  #ffffff !important;
}

/* Page navigation (auto-generated by pages/): the "Stock Toolkit" page
   name and Admin / Game / Help entries. Streamlit's auto-styling can
   pick light-on-light if it thinks dark mode is active; pin to ink so
   the nav is legible on every system. */
[data-testid="stSidebarNav"] a,
[data-testid="stSidebarNav"] span,
[data-testid="stSidebarNavItems"] a,
[data-testid="stSidebarNavItems"] span {
    color: #1a2535 !important;
}
[data-testid="stSidebarNav"] a:hover,
[data-testid="stSidebarNavItems"] a:hover {
    color: #000000 !important;
}

/* Tab labels */
button[data-baseweb="tab"] {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 0.82rem;
    letter-spacing: 0.03em;
    color: #1a2535;
}

/* Code blocks */
code {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 0.8rem;
    background: #e6ecf3;
    color: #1a2535;
    padding: 0.1em 0.3em;
    border-radius: 3px;
}

/* Alert pill */
.pill-green { color: #16a34a; font-weight: 600; }
.pill-red   { color: #dc2626; font-weight: 600; }
.pill-amber { color: #d97706; font-weight: 600; }
.pill-gray  { color: #6b7280; }

/* Divider */
hr { border-color: #d6dde6 !important; }
</style>
"""


# Plotly chart palette — must stay in sync with _THEME_CSS above.
# Centralised here so a future theme swap (e.g. an opt-in dark mode)
# only touches one file. charts.py and game.py import from here.
CHART_BG       = "#fafbfc"   # paper + plot background, matches main surface
CHART_GRID     = "#e2e7ed"   # subtle gridlines on white
CHART_AXIS     = "#d6dde6"   # axis lines, matches CSS border
CHART_INK      = "#1a2535"   # legend text, axis tick labels
CHART_MUTED    = "#5a6b7e"   # secondary text on chart (axis font default)
CHART_FONT     = "IBM Plex Mono"


def setup_page(title: str = "Stock Toolkit") -> None:
    """Apply page config + global CSS. Call as the first line of every
    page's render() (the main app and every file in pages/)."""
    st.set_page_config(
        page_title=title,
        page_icon=icon("app.icon"),
        layout="wide",
        initial_sidebar_state="expanded",
    )
    st.markdown(_THEME_CSS, unsafe_allow_html=True)
