"""Plot output: gnuplot data files and matplotlib charts."""

from pathlib import Path

import pandas as pd

from . import config as cfg
from .config import log

# ─────────────────────────────────────────────
#  PLOTTING
# ─────────────────────────────────────────────

PLOT_FIELDS = ["close", "open", "high", "low", "volume", "vwap", "change_pct"]

# gnuplot tab-file column index for each field (col 1 = date)
_GNUPLOT_COL = {
    "open": 2, "high": 3, "low": 4, "close": 5,
    "volume": 6, "vwap": 7, "change_pct": 8,
}

def _load_plot_data(symbols: list[str], use_csv: bool, field: str,
                     db_path: "Path | None" = None) -> "pd.DataFrame":
    """
    Load daily rows from SQLite or CSV.
    Returns a tidy DataFrame: symbol, source, timestamp, <field>
    db_path overrides cfg.DB_PATH (used by --historical to point at the right DB).
    """
    if use_csv:
        if not cfg.CSV_PATH.exists():
            log.warning("[plot] No CSV file found — run a collection first.")
            return pd.DataFrame()
        df = pd.read_csv(cfg.CSV_PATH)
    else:
        active_db = db_path or cfg.DB_PATH
        if not active_db.exists():
            log.warning(f"[plot] {active_db.name} not found — run a collection first.")
            return pd.DataFrame()
        import sqlite3
        con = sqlite3.connect(active_db)
        try:
            df = pd.read_sql("SELECT * FROM prices", con)
        finally:
            con.close()

    df = df[df["interval"] == "1d"].copy()
    df = df[df["symbol"].isin([s.upper() for s in symbols])]
    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True, errors="coerce")
    df = df.dropna(subset=["timestamp", field])
    df[field] = pd.to_numeric(df[field], errors="coerce")
    df = df.dropna(subset=[field])
    df = df.sort_values("timestamp")
    return df[["symbol", "source", "timestamp", field]].reset_index(drop=True)


# ── gnuplot ───────────────────────────────────────

def plot_gnuplot(symbols: list[str], use_csv: bool, field: str,
                 db_path: "Path | None" = None):
    """
    Writes one .dat file per symbol and a master stock_plot.gp script.

    Each .dat file uses gnuplot index blocks (separated by two blank lines),
    one block per data source, so every source appears as a separate line.

    Run the output with:
        gnuplot stock_plot.gp          # saves stock_plot_<field>.png
        gnuplot -p stock_plot.gp       # interactive window + PNG
    """
    df = _load_plot_data(symbols, use_csv, field, db_path=db_path)
    if df.empty:
        log.warning("[gnuplot] No data available to plot.")
        return

    dat_meta = []   # (symbol, dat_path, [sources])
    cfg.GNUPLOT_DIR.mkdir(parents=True, exist_ok=True)

    # ── write one .dat per symbol ────────────────────────────────────────────────────
    for sym in sorted(df["symbol"].unique()):
        sym_df  = df[df["symbol"] == sym]
        sources = sorted(sym_df["source"].unique())
        dat_path = cfg.GNUPLOT_DIR / f"stock_gnuplot_{sym}.dat"

        with open(dat_path, "w") as f:
            f.write(f"# stock_collector.py — {sym}  field: {field}\n")
            f.write(f"# columns: date  {field}\n\n")
            for src in sources:
                grp = sym_df[sym_df["source"] == src].sort_values("timestamp")
                f.write(f"# --- index block: source={src} ---\n")
                for _, row in grp.iterrows():
                    date_str = str(row["timestamp"])[:10]
                    f.write(f"{date_str}\t{row[field]}\n")
                f.write("\n\n")    # gnuplot index block separator (two blank lines)

        dat_meta.append((sym, dat_path, sources))
        log.info(f"[gnuplot] wrote {dat_path.name}  ({len(sources)} source(s))")

    # ── write master .gp script ────────────────────────────────────────────────────
    gp_path  = cfg.GNUPLOT_DIR / "stock_plot.gp"
    png_name = f"stock_plot_{field}.png"
    ylabel   = field.replace("_", " ").title()
    sym_list = ", ".join(sorted(df["symbol"].unique()))

    with open(gp_path, "w") as f:
        f.write("# Generated by stock_collector.py\n")
        f.write("# Render to PNG:        gnuplot gnuplot-data/stock_plot.gp\n")
        f.write("# Interactive + PNG:    gnuplot -p gnuplot-data/stock_plot.gp\n\n")

        # terminal / output
        f.write("set terminal pngcairo size 1400,600 enhanced font 'Arial,11'\n")
        f.write(f"set output '{png_name}'\n\n")

        # axes
        f.write("set xdata time\n")
        f.write("set timefmt '%Y-%m-%d'\n")
        f.write("set format x '%b %d'\n")
        f.write("set xlabel 'Date'\n")
        f.write(f"set ylabel '{ylabel}'\n")
        f.write(f"set title 'Stock data  —  {ylabel}  ({sym_list})'\n")
        f.write("set grid\n")
        f.write("set key outside right top\n\n")

        # plot command — one entry per (symbol, source) pair
        plot_lines = []
        for sym, dat_path, sources in dat_meta:
            for idx, src in enumerate(sources):
                plot_lines.append(
                    f"  '{dat_path.name}' index {idx}"
                    f" using 1:2 with linespoints pt 7 ps 0.5"
                    f" title '{sym} / {src}'"
                )
        f.write("plot \\\n" + ", \\\n".join(plot_lines) + "\n")

    log.info(f"[gnuplot] wrote {gp_path.name}  →  gnuplot {gp_path.name}")


# ── matplotlib ───────────────────────────────────────────────

def plot_matplotlib(symbols: list[str], use_csv: bool, field: str,
                    db_path: "Path | None" = None):
    """
    Plots with matplotlib: one line per (symbol, source) pair.
    Saves stock_plot_<field>.png in cfg.OUTPUT_DIR and opens an interactive window.
    """
    try:
        import matplotlib.pyplot as plt
        import matplotlib.dates as mdates
    except ImportError:
        log.error("[matplotlib] not installed — run:  pip install matplotlib")
        return

    df = _load_plot_data(symbols, use_csv, field, db_path=db_path)
    if df.empty:
        log.warning("[matplotlib] No data available to plot.")
        return

    fig, ax = plt.subplots(figsize=(14, 6))

    colors  = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728",
               "#9467bd", "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf"]
    markers = ["o", "s", "^", "D", "v", "P", "X", "p", "h", "*"]

    idx = 0
    for sym in sorted(df["symbol"].unique()):
        for src in sorted(df[df["symbol"] == sym]["source"].unique()):
            grp = df[(df["symbol"] == sym) & (df["source"] == src)]
            ax.plot(
                grp["timestamp"], grp[field],
                label=f"{sym} / {src}",
                color=colors[idx % len(colors)],
                marker=markers[idx % len(markers)],
                markersize=3,
                linewidth=1.3,
            )
            idx += 1

    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))
    ax.xaxis.set_major_locator(mdates.AutoDateLocator())
    fig.autofmt_xdate(rotation=35)

    ylabel   = field.replace("_", " ").title()
    sym_list = ", ".join(sorted(df["symbol"].unique()))
    ax.set_xlabel("Date")
    ax.set_ylabel(ylabel)
    ax.set_title(f"Stock data  —  {ylabel}  ({sym_list})")
    ax.legend(loc="upper left", fontsize=8, framealpha=0.75)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()

    cfg.MATPLOTLIB_DIR.mkdir(parents=True, exist_ok=True)
    out_path = cfg.MATPLOTLIB_DIR / f"stock_plot_{field}.png"
    plt.savefig(out_path, dpi=150)
    log.info(f"[matplotlib] saved {out_path.name}")
    plt.show()


