"""
make_docs.py
============
Generates API documentation and module relationship diagrams for the
Stock Toolkit.  Designed to be fully idempotent — same source files
produce byte-identical output by stripping any generation timestamps
from pdoc's HTML before writing.

Tools used:
  pdoc      — HTML API docs from docstrings (pip install pdoc)
  pyreverse — Module/package relationship diagrams (pip install pylint)

Output layout:
  docs/
    stock_collector.html    ← per-module API pages
    stock_analysis.html
    ...
    diagrams/
      packages_StockToolkit.png   ← module dependency graph
      classes_StockToolkit.png    ← class/function relationship diagram

Run:
    python3 make_docs.py                 # generate into docs/
    python3 make_docs.py --out ./pub/docs
    python3 make_docs.py --no-diagrams   # skip pyreverse (faster)
    python3 make_docs.py --dry-run       # show what would run
"""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent

MODULES = [
    "stock_collector",
    "stock_analysis",
    "stock_inventory",
    "stock_score",
    "stock_backtest",
    "stock_alerts",
    "stock_ui",
    "stock_setup",
]

# ─────────────────────────────────────────────
#  HELPERS
# ─────────────────────────────────────────────

# Patterns that break idempotency — stripped from generated HTML.
# Each is a regex matching a full line containing a timestamp or version tag.
TIMESTAMP_PATTERNS = [
    # pdoc footer: "Generated by pdoc 14.x.x on 2026-04-08"
    re.compile(r'.*Generated by pdoc.*'),
    # pdoc meta tag: <meta name="generator" content="pdoc 14.x.x">
    re.compile(r'.*<meta[^>]+name=["\']generator["\'][^>]*>.*'),
    # generic: any ISO datetime in an HTML comment or attribute
    re.compile(r'.*\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}.*'),
]


def check_tool(name: str) -> bool:
    return shutil.which(name) is not None


def run(cmd: list, dry_run: bool, cwd: Path = SCRIPT_DIR) -> bool:
    print(f"  $ {' '.join(str(c) for c in cmd)}")
    if dry_run:
        return True
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  ✗ failed (exit {result.returncode})")
        if result.stderr:
            for line in result.stderr.strip().splitlines():
                print(f"    {line}")
        return False
    return True


# ─────────────────────────────────────────────
#  DOCUMENTATION — pdoc
# ─────────────────────────────────────────────

def strip_timestamps(html_path: Path) -> int:
    """
    Remove lines matching TIMESTAMP_PATTERNS from an HTML file in-place.
    Returns the number of lines removed.
    """
    lines = html_path.read_text(encoding="utf-8").splitlines(keepends=True)
    cleaned = []
    removed = 0
    for line in lines:
        if any(p.match(line.rstrip()) for p in TIMESTAMP_PATTERNS):
            removed += 1
        else:
            cleaned.append(line)
    if removed:
        html_path.write_text("".join(cleaned), encoding="utf-8")
    return removed


def generate_docs(out_dir: Path, dry_run: bool) -> bool:
    """
    Run pdoc with relative .py file paths (avoids embedding absolute paths),
    then strip timestamps to ensure byte-identical output across runs.
    """
    print("\n── API Documentation (pdoc) ─────────────────────────────────")

    if not check_tool("pdoc"):
        print("  ✗ pdoc not found. Install with: pip install pdoc")
        return False

    if not dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    source_files = [
        f"{m}.py"
        for m in MODULES
        if (SCRIPT_DIR / f"{m}.py").exists()
    ]

    cmd = ["pdoc", "--output-dir", str(out_dir)] + source_files
    success = run(cmd, dry_run, cwd=SCRIPT_DIR)

    if success and not dry_run:
        # Strip timestamps for idempotency
        html_files = sorted(out_dir.glob("*.html"))
        total_stripped = 0
        for f in html_files:
            total_stripped += strip_timestamps(f)
        print(f"  ✓ {len(html_files)} HTML pages written to {out_dir}/")
        if total_stripped:
            print(f"    (stripped {total_stripped} timestamp line(s) for idempotency)")
        for f in [out_dir / "index.html"] + html_files:
            if f.exists():
                print(f"    Open: file://{f.resolve()}")
                break
    return success


def generate_diagrams(out_dir: Path, dry_run: bool) -> bool:
    """
    Run pyreverse with relative .py file paths.
    --no-stdlib removed (deprecated in newer pylint; not needed with explicit files).
    """
    print("\n── Relationship Diagrams (pyreverse) ────────────────────────")

    if not check_tool("pyreverse"):
        print("  ✗ pyreverse not found. Install with: pip install pylint")
        return False

    if not check_tool("dot"):
        print("  ✗ graphviz 'dot' not found.")
        print("    macOS:  brew install graphviz")
        print("    Ubuntu: sudo apt install graphviz")
        return False

    diag_dir = out_dir / "diagrams"
    if not dry_run:
        diag_dir.mkdir(parents=True, exist_ok=True)

    source_files = [
        f"{m}.py"
        for m in MODULES
        if (SCRIPT_DIR / f"{m}.py").exists()
    ]

    cmd = [
        "pyreverse",
        "-o", "png",
        "-p", "StockToolkit",
        "-d", str(diag_dir),
    ] + source_files

    success = run(cmd, dry_run, cwd=SCRIPT_DIR)

    if success and not dry_run:
        generated = sorted(diag_dir.glob("*.png"))
        if generated:
            print(f"  ✓ {len(generated)} diagram(s) written to {diag_dir}/")
            for f in generated:
                print(f"    {f.name}")
        else:
            dots = list(diag_dir.glob("*.dot"))
            if dots:
                print("  ⚠  .dot files found but no PNG — is graphviz on PATH?")
            else:
                print(f"  ✗ no output found in {diag_dir}/")
    return success


def main():
    parser = argparse.ArgumentParser(
        description="Generate API docs and diagrams for the Stock Toolkit",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
examples:
  python3 make_docs.py                  # generate into docs/
  python3 make_docs.py --out ./pub/docs # custom output directory
  python3 make_docs.py --no-diagrams    # docs only, skip pyreverse
  python3 make_docs.py --dry-run        # print commands without running
        """
    )
    parser.add_argument("--out", default="docs", metavar="DIR",
                        help="Output directory (default: docs/)")
    parser.add_argument("--no-diagrams", action="store_true",
                        help="Skip pyreverse diagram generation")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print commands without executing them")
    args = parser.parse_args()

    out_dir = SCRIPT_DIR / args.out
    dry_run = args.dry_run

    print(f"\nStock Toolkit — Documentation Generator")
    print(f"Output directory: {out_dir}")
    if dry_run:
        print("(dry run — no files will be written)")

    docs_ok = generate_docs(out_dir, dry_run)
    diag_ok = True
    if not args.no_diagrams:
        diag_ok = generate_diagrams(out_dir, dry_run)

    print(f"\n{'─'*60}")
    if docs_ok and diag_ok:
        print("  ✓ Documentation generation complete")
    else:
        missing = []
        if not docs_ok:
            missing.append("pdoc (pip install pdoc)")
        if not diag_ok:
            missing.append("pylint + graphviz (pip install pylint && brew install graphviz)")
        print("  ⚠  Partial output — install missing tools:")
        for m in missing:
            print(f"       {m}")
    print(f"{'─'*60}\n")


if __name__ == "__main__":
    main()
